### ISSUE TITLE
Intel MKL support

### ISSUE THREAD

**Issue by fredRos** [fredRos/pyFFTW#1]
No single or long double precision supported by Intel. Check this online

**Comment by fredRos** [comment]
On C2PAP, try it out

``` sh
module unload fftw
module load fftw/mpi/v3_mkl110
# in the pyfftw directory
python -c 'import pyfftw'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pyfftw/__init__.py", line 16, in <module>
    from .pyfftw import (
ImportError: libfftw3.so.3: cannot open shared object file: No such file or directory
```

Perhaps not always load FFTW libs in `setup.py`?
